type Gestation {
  id: ID
  user: User
  description: String
  week: Int
  isFinished: Boolean
  createdAt: Float
  createdBy: User
  updatedBy: User
  updatedAt: Float
}

input GestationInput {
  user: ID
  description: String
  week: Int
  isFinished: Boolean
  createdAt: Float
  updatedAt: Float
}

type Query {
  gestations: [Gestation]
  gestation(id: ID!): Gestation
  gestationsByMom(userId: ID!): [Gestation]
}

type Mutation {
  createGestation(data: GestationInput): Gestation
  updateGestation(id: ID!, data: GestationInput): Gestation
  deleteGestation(id: ID!): Gestation
}
