type Gestation {
  id: ID
  description: String
  week: Int
  consultations: [Consultation]
  isFinished: Boolean
  createdAt: Float
  createdBy: User
  updatedBy: User
  updatedAt: Float
}

input GestationInput {
  description: String
  duration: Int
  createdAt: Float
  updatedAt: Float
}
type Query {
  gestations: [Gestation]
  gestation(id: ID!): Gestation
}

type Mutation {
  createGestation(data: GestationInput): Gestation
  updateGestation(id: ID!, data: GestationInput): Gestation
  deleteGestation(id: ID!): Gestation
}

