type Vaccine {
  id: ID
  vaccineCard: VaccineCard
  vaccineTemplate: VaccineTemplate
  description: String
  applicationDate: Float
  isFinished: Boolean
  createdAt: Float
  createdBy: User
  updatedAt: Float
  updatedBy: User
}

type VaccineTemplate {
  id: ID
  name: String
  description: String
  applicationDate: Float
  createdAt: Float
  createdBy: User
  updatedAt: Float
  updatedBy: User
}

input VaccineInput {
  vaccineCard: ID
  vaccineTemplate: ID
  description: String
  applicationDate: Float
  isFinished: Boolean
  createdAt: Float
  updatedAt: Float
}

input VaccineTemplateInput {
  name: String
  description: String
  applicationDate: Float
  createdAt: Float
  updatedAt: Float
}

type Query {
  vaccine(id: ID!): Vaccine
  vaccines: [Vaccine]
  vaccinesByVaccineCard(vaccineCardId: ID!): [Vaccine]
  vaccineTemplate(id: ID!): VaccineTemplate
  vaccineTemplates: [VaccineTemplate]
}

type Mutation {
  createVaccine(data: VaccineInput): Vaccine
  deleteVaccine(id: ID!): Vaccine
  updateVaccine(id: ID!, data: VaccineInput): Vaccine
  createVaccineTemplate(data: VaccineTemplateInput): VaccineTemplate
  deleteVaccineTemplate(id: ID!): VaccineTemplate
  updateVaccineTemplate(id: ID!, data: VaccineTemplateInput): VaccineTemplate
}
