type Consultation {
  id: ID!
  date: Float
  gestation: Gestation
  isFinished: Boolean
  week: Float
  createdAt: Float
  createdBy: User
  updatedBy: User
  updatedAt: Float
}

input ConsultationInput {
  date: Float
  gestation: ID
  week: Float
  isFinished: Boolean
  createdAt: Float
  updatedAt: Float
}

type Query {
  consultations: [Consultation]
  consultation(id: ID!): Consultation
  consultationsByGestation(gestationId: ID!): [Consultation]
}

type Mutation {
  createConsultation(data: ConsultationInput): Consultation
  updateConsultation(
    id: ID!
    data: ConsultationInput!
  ): Consultation
  deleteConsultation(id: ID!): Consultation
}
